/*
 * Team Lentil — Campus Event Management System (MOD004881, Element 010)
 * File: AuditRepository.java
 * Purpose:
 *   Port (Data Access Object) for persisting and querying audit logs.
 * Security & Design Notes:
 *   • Interface hides persistence details behind a stable API boundary.
 *   • No personally identifiable information (PII) is stored beyond
 *     actorUserId and structured JSON in detailsJson.
 *   • Implementations (e.g., InMemoryAuditRepository, JDBC adapter)
 *     must ensure thread safety and consistent ordering by timestamp.
 *   • Methods never return null — they return empty lists instead.
 */
package uk.ac.aru.campusevents.repository;

import uk.ac.aru.campusevents.domain.AuditLog;
import uk.ac.aru.campusevents.dto.AuditFilter;

import java.util.List;

@SuppressWarnings("unused")
public interface AuditRepository {

    /**
     * Persists a new audit log entry.
     *
     * @param log immutable AuditLog object to persist
     * @return assigned ID (generated by the repository)
     */
    int save(AuditLog log);

    /**
     * Queries audit logs using optional filter criteria.
     * Any null filter fields are ignored.
     *
     * @param filter the search filter (may contain null fields)
     * @return list of matching logs, ordered by timestamp (descending)
     */
    List<AuditLog> find(AuditFilter filter);
}



